####################
# Global Repo Settings: https://github.com/probot/settings#usage
# Global Wex Settings: https://github.com/wexinc/global-settings
####################
_extends: 'global-settings:.github/settings.yml'

#Set these to your values so that your topics and description are correct
repository:
  description: Wex Backstage instance for all localized developer portal activities
  topics: backstage, portal, developer, helm

branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts: [ 'sourcehawk-scan' ]
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: [ 'sourcehawk-scan' ]