global:
  imageRegistry: ''
  imagePullSecrets: []
kubeVersion: ''
nameOverride: ''
fullnameOverride: ''
clusterDomain: cluster.local
commonLabels: {}
commonAnnotations: {}
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
ingress:
  enabled: false
  className: ''
  annotations: '{ "nginx.ingress.kubernetes.io/rewrite-target": "/", "nginx.ingress.kubernetes.io/ssl-redirect": "false" }'
  host: ''
backstage:
  replicas: 1
  image:
    registry: ghcr.io/wexinc
    repository: global-backstage
    tag: v1.0.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - gh-secrets
    debug: false
  containerPorts:
    backend: 7007
  command: []
  args: []
  extraAppConfig: []
  extraEnvVars: []
  extraEnvVarsSecrets:
    - backstage-secrets
service:
  type: ClusterIP
  ports:
    backend: 7007
  nodePorts:
    backend: ''
  sessionAffinity: None
  clusterIP: ''
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
networkPolicy:
  enabled: false
  externalAccess:
    from: []
  egressRules:
    customRules: []
postgresql:
  enabled: false
  auth:
    username: bn_backstage
    password: ''
    existingSecret: ''
    secretKeys:
      adminPasswordKey: admin-password
      userPasswordKey: user-password
      replicationPasswordKey: replication-password
  architecture: standalone
secrets:
  AZURE_TOKEN: null
  GITHUB_TOKEN: null
  AUTH_GITHUB_CLIENT_ID: null
  AUTH_GITHUB_CLIENT_SECRET: null
