name: sourcehawk-scan
on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'master'
      - 'release/**'
jobs:
  sourcehawk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Sourcehawk Scan
        uses: optum/sourcehawk-scan-github-action@main