name: Update

on: 
  workflow_dispatch:

  registry_package:
    types: [published, updated]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      

      # - name: Event Information
      #   if: ${{ github.event_name == 'repository_dispatch' }} 
      #   run: |
      #     echo "Received event => '${{ github.event.action }}' "
      #     echo "Metadata ===== "
      #     cat << OBJECT
      #     ${{ toJson(github.event.client_payload) }}
      #     OBJECT
      
      - name: Update Helm Image
        run: |
          cd ./scripts
          ./update-helm-chart-values.sh -c backstage -t 4.x.x -f .backstage.image.tag

      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          commit_message: Auto-update YAML
          commit_author: CI/CD <actions@github.com>