name: Update Chart Version

on: 
  repository_dispatch:
    types: 
      - global-backstage.new_image_tag

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Event Information
        if: ${{ github.event_name == 'repository_dispatch' }} 
        run: |
          echo "Received event => '${{ github.event.action }}' "
          echo "<<<-------- Metadata -------->>> "
          cat << OBJECT
          ${{ toJson(github.event.client_payload) }}
          OBJECT
      
      - name: Update Helm Image
        run: |
          cd ./scripts

          ./update-helm-chart-values.sh \
            -c '${{ github.event.client_payload.chart }}' \
            -t '${{ github.event.client_payload.version }}' \ 
            -f '${{ github.event.client_payload.chart_field }}'
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          commit_message: Auto-update YAML
          commit_author: CI/CD <actions@github.com>
          branch: main